### ISSUE TITLE
Epic: User Authentication and Authorization

### ISSUE THREAD

**Issue by AndersH82** [AndersH82/thesaloon#10]
# User Authentication and Authorization

- [ ] Implement user registration and login functionality.

- [ ] Manage user sessions and authentication tokens.

- [ ] Implement role-based access control for different types of users.

**Comment by AndersH82** [comment]
Done
