### ISSUE TITLE
Epic: Profile Management

### ISSUE THREAD

**Issue by AndersH82** [AndersH82/thesaloon#11]
# Profile Management

- [x] Allow users to create and manage their profiles.

- [x] Enable users to update their profile information.

- [x] Provide a way for users to delete their profiles.

**Comment by AndersH82** [comment]
Done
