### ISSUE TITLE
Epi: Content Creation and Sharing

### ISSUE THREAD

**Issue by AndersH82** [AndersH82/thesaloon#12]
# Content Creation and Sharing

- [x] Enable users to create "shouts" or posts.

- [x] Allow users to like and comment on shouts.

- [x] Implement a system for sharing shouts with other users.

**Comment by AndersH82** [comment]
done
