### ISSUE TITLE
Epic: Image Upload and Management

### ISSUE THREAD

**Issue by AndersH82** [AndersH82/thesaloon#13]
# Image Upload and Management

- [ ] Provide functionality for users to upload images.

- [ ] Display uploaded images in a gallery format.

- [ ] Enable users to delete their uploaded images.

**Comment by AndersH82** [comment]
done
